sudo: required
language: node_js
node_js: '10'
git:
  depth: 1
branches:
  only:
  - master
env:
  global:
  - NODE_OPTIONS="--max_old_space_size=4096"
before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      export DISPLAY=:99.0
      Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      echo "XVFB configured"
    fi
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH=$HOME/.yarn/bin:$PATH
script:
- travis_retry npm start
jobs:
  fast_finish: true
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
